task
golangTroshin/gophermat pull request #1
Opened 2024-09-10 16:43 UTC by golangTroshin

2024-09-19 03:28 UTC, vokinneberg requested changes
Фух 😓, время летит быстро, и мы уже подобрались к первому выпускному проекту! 🎉 По традиции поздравляю с первым ревью, желаю удачи 🍀 и получить удовольствие от реализации проекта 💪. Хочу отметить сильные стороны твоего PR, а также сделать несколько комментариев по поводу того, на что стоит обратить внимание и что можно улучшить. 🤓

**Сильные стороны твоего PR:**

- Очень здорово! Вижу, что первые 4 спринта не прошли даром! 🙌
- В твоём коде нет ничего лишнего, он имеет чёткую структуру, и его приятно читать и легко понимать! 💪
- Реализованный функционал проходит автотесты! ⚡

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

- Было бы здорово реализовать graceful shutdown для сервиса. Также было бы хорошо добавить управление жизненным циклом компонентов при помощи контекста.
- Я бы рекомендовал разобраться с моделью. Мне кажется, где-то не хватает вторичных ключей, а также я бы рекомендовал добавить индексы для тех полей, по которым производится поиск.
- Мне не хватило тестов. Ты действительно покрыл все хендлеры тестами, но по сути эти тесты проверяют только корректную обработку ошибок в хендлерах, так как работают на моках. Было бы хорошо покрыть другие важные компоненты unit-тестами. Особенно это касается accrual service и auth service.
- Для реализации моков я бы рекомендовал применить https://github.com/golang/mock с кодогенерацией. Это позволило бы проверить большее количество кейсов.
- Для проверки ошибок советую использовать либо `errors.Is(...)` вместо `==`, если ты заинтересован в проверке конкретного типа ошибки, либо `errors.As(...)`, если тебе нужно получить ошибку конкретного типа из цепочки ошибок.
- В тестах вместо проверки значений в цикле можно просто сравнить два массива при помощи `cmp.Diff(...)`. Это удобно, так как это покажет все несоответствия в двух структурах.

2024-09-19 03:28 UTC, vokinneberg commented on cmd/gophermart/main.go
> +	})
По-моему `Group(...)` создаст группу с новым middleware  стеком, если хочется сохранить те middleware в стеке, которые уже были использованы, но при этом объединить часть путей можно сделать вот так:

```suggestion
        r.Route("/api/user", func(r chi.Router) {
            r.Use(internal_middleware.AuthMiddleware)
        
            r.Post("/orders", orderHandler.UploadOrder)
            r.Get("/orders", orderHandler.GetOrders)
            r.Get("/balance", balanceHandler.GetUserBalance)
            r.Post("/balance/withdraw", withdrawHandler.Withdraw)
            r.Get("/withdrawals", withdrawHandler.GetWithdrawals)
        })
```

2024-09-19 03:28 UTC, vokinneberg commented on internal/config/config.go
> +func ParseFlags() error {
Я так понимаю, что у тебя переменные окружения имеют приоритет перед флагами. Мне кажется, что флаги  должны иметь приоритет, так как они устанавливаются явно.

2024-09-19 03:28 UTC, vokinneberg commented on internal/handler/auth_handler.go
> +		if err.Error() == "login already exists" {
Можно так же определить ошибку в сервисе `var ErrUserExists = errors.New("user already exists")` и выполнять проверку здесь:
```suggestion
		if errors.Is(err, ErrUserExists) {
```

2024-09-19 03:28 UTC, vokinneberg commented on internal/handler/auth_handler.go
> +	}
Так как структура идентичная имеет смысл вынести ее во внешний скоуп и использовать в обоих хендлерах.

2024-09-19 03:28 UTC, vokinneberg commented on internal/service/auth_service.go
> +type AuthService interface {
Я бы рекомендовал определить интерфейс там,  где он используется. А именно в хендлере.

2024-09-19 03:28 UTC, vokinneberg commented on internal/handler/auth_handler_test.go
> +type MockAuthService struct {
Для мокирования можно применить https://github.com/golang/mock с кодогенерацией.

2024-09-19 03:28 UTC, vokinneberg commented on internal/handler/auth_handler_test.go
> +		"Valid Registration": {
Так как Go автоматически заменяет пробелы на подчеркивания в наименованиях тестов, когда выводит результат я бы не рекомендовал использовать пробелы, или рекомендовал бы сразу заменить их на подчеркивания. В противном случае поиск тестов затрудняется.
```suggestion
		"Valid_Registration": {
```

2024-09-19 03:28 UTC, vokinneberg commented on internal/handler/order_handler.go
> +		http.Error(w, "Internal server error", http.StatusInternalServerError)
Здесь можно использовать либо `errors.Is(...)` вместо `==`, если ты заинтересован в проверке конкретного типа ошибки, либо `errors.As(...)`  если тебе получить ошибку конкретного типа из цепочки ошибок.
```suggestion
		if errors.Is(err, service.ErrOrderExistsSameUser) {
			w.WriteHeader(http.StatusOK)
			return
		} else if errors.Is(err, service.ErrOrderExistsDifferentUser) {
			http.Error(w, "Order already uploaded by another user", http.StatusConflict)
			return
		}
		http.Error(w, "Internal server error", http.StatusInternalServerError)
```

2024-09-19 03:28 UTC, vokinneberg commented on internal/handler/order_handler.go
> +	w.Header().Set("Content-Type", "application/json")
Статус будет по-умолчанию `200 OK`, но для наглядности возможно стоит установить его явно?

2024-09-19 03:28 UTC, vokinneberg commented on internal/handler/order_handler_test.go
> +		"Valid Order Upload": {
По-моему тут пропустили кейсы кодом `409` и с кодом `400`?

2024-09-19 03:28 UTC, vokinneberg commented on internal/handler/withdrawal_handler.go
> +	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
Мне кажется это скорее `400 BadRequest`, чем `422`.

2024-09-19 03:28 UTC, vokinneberg commented on internal/handler/withdrawal_handler.go
> +		ProcessedAt: time.Now(),
Мне кажется стоит форматировать данные консистентно.
```suggestion
		ProcessedAt: time.Now().Format(time.RFC3339),
```

2024-09-19 03:28 UTC, vokinneberg commented on internal/handler/withdrawal_handler_test.go
> +		"Valid Withdrawal": {
Стоит добавить проверку кейса с кодом `400`?

2024-09-19 03:28 UTC, vokinneberg commented on internal/handler/withdrawal_handler_test.go
> +				}
Вместо проверки значений в цикле можно просто сравнить два массива. Это удобно, так как это покажет все несоответствия в двух структурах.

```suggestion
                if diff := cmp.Diff(tc.expectedResponse, response); diff != "" {
			t.Errorf("Unexpected response (-expected +got):\n%s", diff)
		}
```

2024-09-19 03:28 UTC, vokinneberg commented on internal/model/balance.go
> +	Current   float64 `gorm:"not null;default:0"`
По-моему `gorm` автоматом навесит `NOT NULL` констрейнт на все колонки, которые не указатель.

2024-09-19 03:28 UTC, vokinneberg commented on internal/model/withdrawal.go
> +	UserID      uint      `gorm:"not null"`
Это не должен быть Foreign Key на `User`?

2024-09-19 03:28 UTC, vokinneberg commented on internal/model/withdrawal.go
> +	Order       string    `gorm:"not null"`
Это не должен быть Foreign Key на `Order`?

2024-09-19 03:28 UTC, vokinneberg commented on internal/model/user.go
> +	BalanceID uint   `gorm:"not null"`
Мне кажется, что если у нас установлен Foreign Key на таблице `Balance`, то нет необходимости явно добавлять поле `BalanceID`. 

2024-09-19 03:28 UTC, vokinneberg commented on internal/model/order.go
> +	UserID     uint      `gorm:"not null"`
Это не должен быть Foreign Key на `User`?

2024-09-19 03:28 UTC, vokinneberg commented on cmd/gophermart/main.go
> +	go service.StartPolling(db, 5*time.Second, 2)
Было бы здорово задавать количество воркеров и интервал опроса при помощи конфигурации.

2024-09-19 03:28 UTC, vokinneberg commented on internal/service/accrual_service.go
> +			pauseMux.Unlock()
Мне кажется, можно попробовать немного оптимизировать, если использовать RWLock.

```suggestion
			{
				pauseMux.Lock()
				defer pauseMux.Unlock()
				
				pause = true
			
				log.Printf("Too many requests, pausing for %d seconds", retryAfterSeconds)
				time.Sleep(time.Duration(retryAfterSeconds) * time.Second)

				pause = false
			}
```

2024-09-19 03:28 UTC, vokinneberg commented on internal/service/accrual_service.go
> +func fetchOrderStatus(orderNumber string) (*APIResponse, error) {
Задумка с паузой интересная! Я бы рекомендовал так же обратить внимание на библиотеку "[golang.org/x/time/rate](http://golang.org/x/time/rate)", в которой есть rate limiter, который позволяет ограничить количество операций в секунду, например (если мы уже знаем, сколько операцией позволяет выполнять вызываемый сервис):

```go
func main() {
    // Create a rate limiter that allows 5 requests per second.
    rateLimiter := rate.NewLimiter(5, 1)

    // WaitGroup to wait for all goroutines to finish.
    var wg sync.WaitGroup

    // Simulate the number of simultaneous requests.
    numberOfGoroutines := 10

    // URL of the external API.
    url := "<https://api.example.com/data>"

    for i := 0; i < numberOfGoroutines; i++ {
        wg.Add(1)
        go func(id int) {
            defer wg.Done()

            // Wait until the rate limiter allows the next request.
            if err := rateLimiter.Wait(nil); err != nil {
                fmt.Printf("Goroutine #%d: Rate limiter error: %v\\n", id, err)
                return
            }

            // Make the HTTP GET request.
            resp, err := http.Get(url)
            if err != nil {
                fmt.Printf("Goroutine #%d: Error making request: %v\\n", id, err)
                return
            }
            defer resp.Body.Close()

            // Check the response status.
            if resp.StatusCode == http.StatusOK {
                fmt.Printf("Goroutine #%d: Received response at time %v\\n", id, time.Now())
            } else {
                fmt.Printf("Goroutine #%d: Received unexpected status: %v\\n", id, resp.Status)
            }
        }(i)
    }

    // Wait for all goroutines to finish.
    wg.Wait()
}
```

2024-09-19 03:28 UTC, vokinneberg commented on internal/service/accrual_service.go
> +		}
В случае с RWLock, мы все еще можем читать, но записывать в этот момент никто не сможет. Таким образом другие читатели не блокируются.

```suggestion
        pauseMux.RLock()
	paused := pause
	pauseMux.RUnlock()

	if paused {
		log.Println("Waiting for pause to be lifted...")
		for paused {
			time.Sleep(1 * time.Second)
			pauseMux.Lock()
			paused = pause
			pauseMux.RUnlock()
		}
	}
```

2024-09-19 03:28 UTC, vokinneberg commented on cmd/gophermart/main.go
> +	if err := http.ListenAndServe(config.Options.ServerAddress, getRouter(db)); err != nil {
Было бы здорово реализовать graceful shutdown для сервиса.

2024-09-21 07:36 UTC, golangTroshin commented on internal/model/user.go
> +	BalanceID uint   `gorm:"not null"`
![image](https://github.com/user-attachments/assets/54cbe0f8-cb88-4c82-96cb-9741cfae24fa)

я так понимаю это просто синтаксис gorm чтобы как раз задать foreign key

2024-09-21 11:01 UTC, golangTroshin commented on internal/model/balance.go
> +	Current   float64 `gorm:"not null;default:0"`
протестил, не проставляет

2024-09-21 11:02 UTC, golangTroshin commented on internal/model/withdrawal.go
> +	Order       string    `gorm:"not null"`
это не стал связывать, так как автотесты считают что запрос должен проходить даже для не существующих заказов

2024-09-27 13:36 UTC, golangTroshin commented on internal/service/accrual_service.go
> +func fetchOrderStatus(orderNumber string) (*APIResponse, error) {
я так понимаю rateLimiter подходит только если знаем сколько запросов в секунду мы можем отправлять, но в нашем случае accural некий черный ящик без этой информации поэтому решил оставить реализацию с паузой, но взял на заметку рэйт лимитер для других ситуаций в будущем, спасибо!

2024-10-05 16:32 UTC, vokinneberg approved these changes
Поздравляю, ты отлично справился с первым выпускным проектом! 🎉 Ты реализовал множество предложений из предыдущего ревью — здорово! 👍 Твой уровень владения Go значительно вырос. Твоё приложение стало лучше, функциональнее и проходит все тесты. 🚀

**Сильные стороны твоего PR:**

- Здорово, что ты реализовал graceful shutdown 🙌
- Ты добавил дополнительные тест-кейсы. 👍
- Ты использовал кодогенерацию для мокирования ⚡

**На что стоит обратить внимание и что можно улучшить:**

- Хранение и операции с деньгами через типы с плавающей точкой могут привести к неявным ошибкам из-за округлений при вычислениях. Рекомендую использовать либо minimal currency unit (хранить копейки вместо рублей в целочисленном типе и форматировать при необходимости), либо тип `decimal`. Так как в Go нет встроенного `decimal` типа, можно использовать сторонние библиотеки.
- По-поему ты не доабвил индексы на поля, по которым происходит поиск.

2024-10-05 16:32 UTC, vokinneberg commented on internal/handler/auth_handler.go
> +		if errors.Is(err, service.ErrUserExists) {
👍

2025-02-18 10:26 UTC, merged